### ISSUE TITLE
Stock Inventory 16

### ISSUE THREAD

**Issue by amg44a** [dhongu/deltatech#1027]
In the Ludo 16 inventory audit module, when the inventory quantity is modified and the confirmation button is post, the following message appears:
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo-server/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/odoo-server/odoo/http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo-server/odoo/http.py", line 1815, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo-server/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/odoo-server/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-server/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo-server/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/custom_app/deltatech_stock_inventory/models/stock_inventory.py", line 162, in action_validate
    self._action_done()
  File "/opt/odoo/custom_app/deltatech_stock_inventory/models/stock.py", line 46, in _action_done
    super(StockInventory, self)._action_done()
  File "/opt/odoo/custom_app/deltatech_stock_inventory/models/stock_inventory.py", line 185, in _action_done
    self.action_check()
  File "/opt/odoo/custom_app/deltatech_stock_inventory/models/stock.py", line 42, in action_check
    res = super(StockInventory, self).action_check()
  File "/opt/odoo/custom_app/deltatech_stock_inventory/models/stock_inventory.py", line 205, in action_check
    inventory.line_ids._generate_moves()
  File "/opt/odoo/custom_app/deltatech_stock_inventory/models/stock.py", line 125, in _generate_moves
    moves = super(StockInventoryLine, self)._generate_moves()
  File "/opt/odoo/custom_app/deltatech_stock_inventory/models/stock_inventory.py", line 713, in _generate_moves
    return self.env["stock.move"].create(vals_list)
  File "<decorator-gen-216>", line 2, in create
  File "/opt/odoo/odoo-server/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo-server/addons/mrp/models/stock_move.py", line 291, in create
    return super().create(vals_list)
  File "<decorator-gen-173>", line 2, in create
  File "/opt/odoo/odoo-server/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo-server/addons/stock/models/stock_move.py", line 657, in create
    return super().create(vals_list)
  File "<decorator-gen-65>", line 2, in create
  File "/opt/odoo/odoo-server/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_fields.py", line 670, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/opt/odoo/odoo-server/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo-server/odoo/models.py", line 3954, in create
    records = self._create(data_list)
  File "/opt/odoo/odoo-server/odoo/models.py", line 4191, in _create
    field.create([
  File "/opt/odoo/odoo-server/odoo/fields.py", line 4248, in create
    self.write_batch(record_values, True)
  File "/opt/odoo/odoo-server/odoo/fields.py", line 4274, in write_batch
    return self.write_real(records_commands_list, create)
  File "/opt/odoo/odoo-server/odoo/fields.py", line 4465, in write_real
    flush()
  File "/opt/odoo/odoo-server/odoo/fields.py", line 4421, in flush
    comodel.create(to_create)
  File "<decorator-gen-224>", line 2, in create
  File "/opt/odoo/odoo-server/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo-server/addons/stock_account/models/stock_move_line.py", line 17, in create
    move_lines = super(StockMoveLine, self).create(vals_list)
  File "<decorator-gen-215>", line 2, in create
  File "/opt/odoo/odoo-server/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo-server/addons/mrp/models/stock_move.py", line 43, in create
    res = super(StockMoveLine, self).create(values)
  File "<decorator-gen-174>", line 2, in create
  File "/opt/odoo/odoo-server/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo-server/addons/stock/models/stock_move_line.py", line 292, in create
    mls = super().create(vals_list)
  File "<decorator-gen-65>", line 2, in create
  File "/opt/odoo/odoo-server/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_fields.py", line 670, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/opt/odoo/odoo-server/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo-server/odoo/models.py", line 3910, in create
    raise ValueError("Invalid field %r on model %r" % (key, self._name))
ValueError: Invalid field 'product_uom_qty' on model 'stock.move.line'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://62.72.29.101:8016/web/assets/debug/web.assets_backend.js:10360:19) (/web/static/src/core/network/rpc_service.js:34)
    at XMLHttpRequest.<anonymous> (http://62.72.29.101:8016/web/assets/debug/web.assets_backend.js:10413:27) (/web/static/src/core/network/rpc_service.js:87)

**Comment by dhongu** [comment]
I have solved this error
