### ISSUE TITLE
[Odoo 16 Vendor Stock] AttributeError: 'stock.picking' object has no attribute 'move_lines'

### ISSUE THREAD

**Issue by majenkotech** [dhongu/deltatech#931]
When trying to receive stock from a purchase order:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1583, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 134, in retrying
    result = func()
             ^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1610, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1807, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 696, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/addons/deltatech_stock_date/wizard/stock_immediate_transfer.py", line 21, in process
    return super(StockImmediateTransfer, self.with_context(force_period_date=self.date)).process()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/addons/stock/wizard/stock_immediate_transfer.py", line 63, in process
    return pickings_to_validate.with_context(skip_immediate=True).button_validate()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/addons/stock/models/stock_picking.py", line 1086, in button_validate
    pickings_not_to_backorder.with_context(cancel_backorder=True)._action_done()
  File "/usr/lib/python3/dist-packages/odoo/addons/sale_stock/models/stock.py", line 84, in _action_done
    res = super()._action_done()
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/addons/deltatech_stock_date/models/stock.py", line 63, in _action_done
    self.move_lines.write({"date": use_date})  # 'date_expected': use_date,
    ^^^^^^^^^^^^^^^
AttributeError: 'stock.picking' object has no attribute 'move_lines'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPCError@https://web1.majenko.co.uk/web/assets/493-0ddf4c9/web.assets_backend.min.js:966:274
    makeErrorFromResponse@https://xxxxxxxx/web/assets/493-0ddf4c9/web.assets_backend.min.js:970:163
    jsonrpc/promise</<@https://xxxxxxxx/web/assets/493-0ddf4c9/web.assets_backend.min.js:978:34
```

I *think* in 16.0 it's now `move_line_ids`

**Comment by dhongu** [comment]
done
